/**
 * Cards that have received an errata, carrying their ORIGINAL pre-errata text.
 *
 * Generated from cards.csv, which is the source of truth for this table.
 *
 * - `id` is the passcode printed on the card. Its scan on yugi.wiki shows the
 *   current, post-errata text.
 * - `errataId` is our internal id for the pre-errata printing (always id + 20).
 *   Its scan shows the original text, which matches `desc` below, so it is the
 *   image to display for a format frozen before the errata.
 * - `koid` is Konami's own id, which the rulings database keys on. It is not
 *   the passcode.
 * - `desc` is the pre-errata text, occasionally with [b]...[/b] around defined
 *   game terms.
 */
export type ErrataCard = {
  id: number;
  name: string;
  errataId: number;
  koid: number;
  desc: string;
};

export const ERRATAS: readonly ErrataCard[] = [
  {
    id: 2111707,
    name: "XY-Dragon Cannon",
    errataId: 2111727,
    koid: 5553,
    desc: `"X-Head Cannon" + "Y-Dragon Head"
This card can only be Special Summoned from your Fusion Deck by removing from play the above cards on your side of the field. (You do not use "Polymerization"). This card cannot be Special Summoned from the Graveyard. Discard 1 card from your hand to destroy 1 face-up Spell or Trap Card on your opponent's side of the field.`,
  },
  {
    id: 2134346,
    name: "Asura Priest",
    errataId: 2134366,
    koid: 5381,
    desc: `This card cannot be Special Summoned. This card returns to its owner's hand during the End Phase of the turn it is Normal Summoned or flipped face-up. This card can attack all monsters your opponent controls once each. This monster cannot attack directly if it has already attacked a monster.`,
  },
  {
    id: 2356994,
    name: "Great Long Nose",
    errataId: 2357014,
    koid: 5378,
    desc: `This card cannot be Special Summoned. This card returns to the owner's hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. If this card inflicts Battle Damage to your opponent's Life Points, your opponent skips their next Battle Phase.`,
  },
  {
    id: 2420921,
    name: "Shire, Lightsworn Spirit",
    errataId: 2420941,
    koid: 8595,
    desc: `This card gains 300 ATK for each "Lightsworn" monster with a different name in your Graveyard. During each of your End Phases, send the top 2 cards of your Deck to the Graveyard.`,
  },
  {
    id: 3370104,
    name: "Cyber Phoenix",
    errataId: 3370124,
    koid: 6663,
    desc: `While this card is in face-up Attack Position on your side of the field, negate the effects of any Spell or Trap Card that targets 1 Machine-Type monster on your side of the field. When this face-up card on the field attacks or is attacked, and it is destroyed as a result of battle and sent to the Graveyard, you can draw 1 card from your Deck.`,
  },
  {
    id: 5043010,
    name: "Firewall Dragon",
    errataId: 5043030,
    koid: 13082,
    desc: `2+ monsters
Once while face-up on the field (Quick Effect): You can target monsters on the field and/or GY up to the number of monsters co-linked to this card; return them to the hand. If a monster this card points to is destroyed by battle or sent to the GY: You can Special Summon 1 monster from your hand.`,
  },
  {
    id: 5645210,
    name: "Splendid Venus",
    errataId: 5645230,
    koid: 7347,
    desc: `All non-Fairy-Type monsters lose 500 ATK and DEF. The activation and effects of your Spell and Trap Cards cannot be negated.`,
  },
  {
    id: 7183277,
    name: "Aurkus, Lightsworn Druid",
    errataId: 7183297,
    koid: 7796,
    desc: `Lightsworn" monsters cannot be targeted by effects. During each of your End Phases, send the top 2 cards of your Deck to the Graveyard.`,
  },
  {
    id: 7391448,
    name: "Goyo Guardian",
    errataId: 7391468,
    koid: 7736,
    desc: `1 Tuner + 1 or more non-Tuner monsters
When this card destroys an opponent's monster by battle and sends it to the Graveyard, you can Special Summon that monster to your side of the field in face-up Defense Position.`,
  },
  {
    id: 7563579,
    name: "Performage Plushfire",
    errataId: 7563599,
    koid: 11960,
    desc: `P
If a "Performage" monster(s) you control is destroyed by battle or card effect: You can Special Summon this card from your Pendulum Zone, then take 500 damage. You can only use this effect of "Performage Plushfire" once per turn.
E
If this card on the field is destroyed by battle or card effect: You can Special Summon 1 "Performage" monster from your hand or Deck, except "Performage Plushfire".`,
  },
  {
    id: 8131171,
    name: "Sinister Serpent",
    errataId: 8131191,
    koid: 4481,
    desc: `During your Standby Phase, if a "Sinister Serpent" exists in your Graveyard, you can return the "Sinister Serpent" to your hand.`,
  },
  {
    id: 9126351,
    name: "Swap Frog",
    errataId: 9126371,
    koid: 8469,
    desc: `You can discard 1 WATER monster to Special Summon this card from your hand. When this card is Summoned, you can select and send 1 Level 2 or lower Aqua-Type WATER monster from your Deck or your side of the field to the Graveyard. Once per turn, you can return 1 monster you control to your hand to Normal Summon 1 "Frog" monster, except "Swap Frog" or "Frog the Jam", in addition to your Normal Summon or Set this turn.`,
  },
  {
    id: 9596126,
    name: "Chaos Sorcerer",
    errataId: 9596146,
    koid: 5833,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 1 LIGHT and 1 DARK monster in your Graveyard. Once per turn, during your Main Phase, you can remove from play 1 face-up monster on the field. If you activate this effect, this card cannot attack this turn.`,
  },
  {
    id: 9995766,
    name: "Imperial Custom",
    errataId: 9995786,
    koid: 8357,
    desc: `Face-up Continuous Traps [b]cannot[/b] be destroyed by battle or card effect, except "Imperial Custom". [b]You can[/b] only control 1 "Imperial Custom".`,
  },
  {
    id: 10248389,
    name: "Cyber Blader",
    errataId: 10248409,
    koid: 6485,
    desc: `Etoile Cyber" + "Blade Skater"
A Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. While your opponent controls only 1 monster, this card cannot be destroyed by battle. While your opponent controls only 2 monsters, double this card's ATK. While your opponent controls only 3 monsters, negate the effects of your opponent's Spell, Trap, and Effect Monster Cards.`,
  },
  {
    id: 12538374,
    name: "Treeborn Frog",
    errataId: 12538394,
    koid: 6603,
    desc: `If this card is in your Graveyard during your Standby Phase and you control no Spell or Trap Cards, you can Special Summon it. This effect cannot be activated if you control a face-up "Treeborn Frog".`,
  },
  {
    id: 12923641,
    name: "Swords of Concealing Light",
    errataId: 12923661,
    koid: 6268,
    desc: `When you activate this card, change all monsters on your opponent's side of the field to face-down Defense Position. Monsters on your opponent's side of the field cannot change their Battle Positions. Destroy this card during your 2nd Standby Phase after activation.`,
  },
  {
    id: 13955608,
    name: "Stronghold the Moving Fortress",
    errataId: 13955628,
    koid: 6153,
    desc: `After activation, Special Summon this card in Defense Position; it is treated as an Effect Monster Card (Machine-Type/EARTH/Level 4/ATK 0/DEF 2000). While you control "Green Gadget", "Red Gadget", and "Yellow Gadget", this card's ATK becomes 3000. (This card is still treated as a Trap Card.)`,
  },
  {
    id: 14878871,
    name: "Rescue Cat",
    errataId: 14878891,
    koid: 6262,
    desc: `You can send this face-up card to the Graveyard to Special Summon 2 Level 3 or lower Beast-Type monsters from your Deck. Those monsters are destroyed during the End Phase.`,
  },
  {
    id: 15800838,
    name: "Mind Crush",
    errataId: 15800858,
    koid: 6147,
    desc: `Declare 1 card name. If that card is in your opponent's hand, they must discard all copies of it in their hand. If it is not, you randomly discard 1 card.`,
  },
  {
    id: 15894048,
    name: "Ultimate Tyranno",
    errataId: 15894068,
    koid: 6777,
    desc: `If this card is in Attack Position at the beginning of your Battle Phase, first, you can and must attack all monsters on Your opponent's side of the field once each with this card.`,
  },
  {
    id: 16226786,
    name: "Night Assailant",
    errataId: 16226806,
    koid: 6042,
    desc: `FLIP: Select 1 monster on your opponent's side of the field and destroy it. When this card is sent directly from your hand to the Graveyard, return 1 Flip Effect Monster from your Graveyard to your hand.`,
  },
  {
    id: 16227556,
    name: "Inspection",
    errataId: 16227576,
    koid: 4967,
    desc: `During your opponent's Standby Phase, you can pay 500 Life Points to randomly select 1 card in your opponent's hand and look at it.`,
  },
  {
    id: 16762927,
    name: "Gravekeeper's Servant",
    errataId: 16762947,
    koid: 4893,
    desc: `Unless your opponent sends 1 card from the top of his/her Deck to the Graveyard, he/she [b]cannot[/b] declare an attack.`,
  },
  {
    id: 17484499,
    name: "Exchange of the Spirit",
    errataId: 17484519,
    koid: 5360,
    desc: `Activate only while there are 15 or more cards in your Graveyard. Pay 1000 Life Points. Both players swap the card(s) in their Graveyard with the card(s) in their Deck. Then, both players shuffle their Decks.`,
  },
  {
    id: 17655904,
    name: "Burst Stream of Destruction",
    errataId: 17655924,
    koid: 5979,
    desc: `If you control "Blue-Eyes White Dragon": [b]Destroy[/b] all monsters your opponent controls. "Blue-Eyes White Dragon" you control [b]cannot[/b] attack the turn you activate this card.`,
  },
  {
    id: 20932152,
    name: "Quickdraw Synchron",
    errataId: 20932172,
    koid: 8439,
    desc: `You can send 1 monster from your hand to the Graveyard and Special Summon this card from your hand. You can substitute this card for any 1 "Synchron" Tuner monster for a Synchro Summon. This card cannot be used as a Synchro Material Monster, except for the Synchro Summon of a monster that lists a "Synchron" monster as a Tuner monster.`,
  },
  {
    id: 21502796,
    name: "Ryko, Lightsworn Hunter",
    errataId: 21502816,
    koid: 7595,
    desc: `FLIP: You can destroy 1 card on the field. Send the top 3 cards of your Deck to the Graveyard.`,
  },
  {
    id: 21593977,
    name: "Makyura the Destructor",
    errataId: 21593997,
    koid: 5285,
    desc: `During the turn this card is sent to the Graveyard, the owner of this card can activate Trap Card(s) from his/her hand.`,
  },
  {
    id: 21785144,
    name: "Gragonith, Lightsworn Dragon",
    errataId: 21785164,
    koid: 7598,
    desc: `This card gains 300 ATK and DEF for each "Lightsworn" monster with a different name in your Graveyard. During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent. During each of your End Phases, send the top 3 cards of your Deck to the Graveyard.`,
  },
  {
    id: 22446869,
    name: "Mermail Abyssteus",
    errataId: 22446889,
    koid: 10471,
    desc: `You can discard 1 other WATER monster to the GY; Special Summon this card from your hand. If Summoned this way: Add 1 Level 4 or lower "Mermail" monster from your Deck to your hand. You can only use this effect of "Mermail Abyssteus" once per turn.`,
  },
  {
    id: 22624373,
    name: "Lyla, Lightsworn Sorceress",
    errataId: 22624393,
    koid: 7592,
    desc: `You can change this card from face-up Attack Position to face-up Defense Position and destroy 1 Spell or Trap Card your opponent controls. If you activate this effect, this card's battle position cannot be changed until the end of your next turn, except with a card effect. During each of your End Phases, send the top 3 cards of your Deck to the Graveyard.`,
  },
  {
    id: 23265594,
    name: "Heavy Mech Support Platform",
    errataId: 23265614,
    koid: 6181,
    desc: `Once per turn, during your Main Phase, you can equip this card to a Machine-Type monster you control as an Equip Card, OR unequip it and Special Summon it in face-up Attack Position. While equipped to a monster by this effect, that monster gains 500 ATK and DEF. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed, this card is destroyed instead.)`,
  },
  {
    id: 24294108,
    name: "Burning Land",
    errataId: 24294128,
    koid: 5126,
    desc: `Destroy all Field Spell Cards on the field. Inflict 500 points of damage to Each player's Life Points during his/her Standby Phase.`,
  },
  {
    id: 25119460,
    name: "YZ-Tank Dragon",
    errataId: 25119480,
    koid: 5626,
    desc: `"Y-Dragon Head" + "Z-Metal Tank"
This card can only be Special Summoned from your Fusion Deck by removing from play the above cards on your side of the field. (You do not use "Polymerization"). This card cannot be Special Summoned from the Graveyard. Discard 1 card from your hand to destroy 1 face-down Monster Card on your opponent's side of the field.`,
  },
  {
    id: 25862681,
    name: "Ancient Fairy Dragon",
    errataId: 25862701,
    koid: 8090,
    desc: `1 Tuner + 1 or more non-Tuner monsters
Once per turn, you can Special Summon 1 Level 4 or lower monster from your hand. You cannot conduct your Battle Phase the turn you activate this effect. Once per turn, you can destroy a Field Spell Card. If you do, gain 1000 Life Points, and you can add 1 Field Spell Card from your Deck to your hand.`,
  },
  {
    id: 26202165,
    name: "Sangan",
    errataId: 26202185,
    koid: 4054,
    desc: `When this card is sent from the field to the Graveyard, add 1 monster with 1500 or less ATK from your Deck to your hand.`,
  },
  {
    id: 28563545,
    name: "Dragon Seeker",
    errataId: 28563565,
    koid: 4506,
    desc: `When a "Dragon Seeker" is changed to Attack Position: You can target 1 face-up Dragon-Type monster on the field; destroy it.`,
  },
  {
    id: 29071332,
    name: "Armory Arm",
    errataId: 29071352,
    koid: 7987,
    desc: `1 Tuner + 1 or more non-Tuner monsters
Once per turn, you can equip this card to a monster OR unequip it to Special Summon this card in face-up Attack Position. While equipped to a monster by this effect, that monster gains 1000 ATK. When the equipped monster destroys a monster by battle and sends it to the Graveyard, inflict damage to your opponent equal to the destroyed monster's ATK.`,
  },
  {
    id: 29389368,
    name: "Nutrient Z",
    errataId: 29389388,
    koid: 5403,
    desc: `During damage calculation, [b]when[/b] you are about to take 2000 or more battle damage: Gain 4000 LP first.`,
  },
  {
    id: 29762407,
    name: "Temple of the Kings",
    errataId: 29762427,
    koid: 5231,
    desc: `The controller of this card can activate Trap Cards the same turn they are Set. If you control "Mystical Beast of Serket" and this card, you can send both to the Graveyard to Special Summon 1 monster from your hand, Deck, or Extra Deck.`,
  },
  {
    id: 32646477,
    name: "Dark Strike Fighter",
    errataId: 32646497,
    koid: 8035,
    desc: `1 Tuner + 1 or more non-Tuner monsters
You can Tribute 1 monster to inflict damage to your opponent equal to its Level x 200.`,
  },
  {
    id: 34471458,
    name: "Fortune Lady Light",
    errataId: 34471478,
    koid: 8301,
    desc: `This card's ATK and DEF are equal to its Level x 200. During each of your Standby Phases, increase the Level of this card by 1 (max 12). When this card is removed from the field by a card effect, you can Special Summon 1 "Fortune Lady" monster from your Deck.`,
  },
  {
    id: 37580756,
    name: "Michizure",
    errataId: 37580776,
    koid: 4939,
    desc: `[b]When[/b] a monster is sent from the field to your GY, even during the Damage Step: [b]Target[/b] 1 monster on the field; [b]destroy[/b] it.`,
  },
  {
    id: 38369349,
    name: "Manga Ryu-Ran",
    errataId: 38369369,
    koid: 4733,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned while you control "Toon World". You can Special Summon this card from your hand (but Tributes are required if it is Level 5 or higher). This card cannot attack during the turn it is Summoned. This card cannot attack unless you pay 500 Life Points. When "Toon World" is destroyed, destroy this card. If your opponent doesn't control a Toon Monster, this card can attack your opponent directly. If your opponent controls a face-up Toon Monster, you must select it as an attack target.`,
  },
  {
    id: 38538445,
    name: "Fushi No Tori",
    errataId: 38538465,
    koid: 5382,
    desc: `This card cannot be Special Summoned. This card returns to the owner's hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. When this card inflicts Battle Damage to your opponent's Life Points, increase your Life Points by an amount equal to the Battle Damage.`,
  },
  {
    id: 40044918,
    name: "Elemental HERO Stratos",
    errataId: 40044938,
    koid: 6784,
    desc: `When this card is Normal or Special Summoned, you can select and activate 1 of these effects:
● Destroy Spell or Trap Cards on the field up to the number of "Elemental Hero", "Destiny Hero" and "Evil Hero" monsters you control (not counting this card).
● Select and add 1 "Elemental Hero", "Destiny Hero" or "Evil Hero" monster from your Deck to your hand.`,
  },
  {
    id: 40172183,
    name: "Narrow Pass",
    errataId: 40172203,
    koid: 5545,
    desc: `This card can only be activated [b]when[/b] both players have 2 monsters or less on their respective sides of the field. Both players can only Normal Summon up to 2 additional monsters on their sides of the field.`,
  },
  {
    id: 40473581,
    name: "Susa Soldier",
    errataId: 40473601,
    koid: 5376,
    desc: `This card cannot be Special Summoned. This card returns to the owner's hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. The Battle Damage this card inflicts to your opponent's Life Points is halved.`,
  },
  {
    id: 40695128,
    name: "Maharaghi",
    errataId: 40695148,
    koid: 5373,
    desc: `This card cannot be Special Summoned. This card returns to the owner's hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. If this card is Normal Summoned or flipped face-up, look at 1 card on the top of your Deck during your next Draw Phase (before you draw), and return the card to the top or the bottom of your Deck.`,
  },
  {
    id: 40737112,
    name: "Dark Magician of Chaos",
    errataId: 40737132,
    koid: 5880,
    desc: `When this card is Normal or Special Summoned, you can select and add 1 Spell Card from your Graveyard to your hand. Monsters this card destroys by battle are removed from play instead of going to the Graveyard. If this face-up card is destroyed or removed from the field, it is removed from play.`,
  },
  {
    id: 41006930,
    name: "Strike Ninja",
    errataId: 41006950,
    koid: 5817,
    desc: `You can remove this card from play until the End Phase of this turn by removing from play 2 DARK monsters in your Graveyard. You can use this effect during either player's turn. You can only use this effect once per turn.`,
  },
  {
    id: 42940404,
    name: "Machina Gearframe",
    errataId: 42940424,
    koid: 8693,
    desc: `When this card is Normal Summoned, you can add 1 "Machina" monster, except "Machina Gearframe", from your Deck to your hand. Once per turn, during your Main Phase, you can equip this card to a Machine-Type monster you control as an Equip Card, OR unequip it to Special Summon this card in face-up Attack Position. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed, destroy this card instead.)`,
  },
  {
    id: 43586926,
    name: "Twin-Headed Behemoth",
    errataId: 43586946,
    koid: 5030,
    desc: `If this card is destroyed and sent from the field to the Graveyard, Special Summon it during the End Phase of this turn with 1000 ATK and 1000 DEF. You can only use this effect once per Duel.`,
  },
  {
    id: 44178886,
    name: "Ehren, Lightsworn Monk",
    errataId: 44178906,
    koid: 7797,
    desc: `If this card attacks a Defense Position monster, return that monster to its owner's Deck before damage calculation. During each of your End Phases, send the top 3 cards of your Deck to the Graveyard.`,
  },
  {
    id: 45247637,
    name: "Mark of the Rose",
    errataId: 45247657,
    koid: 7903,
    desc: `Remove from play 1 Plant-Type monster from your Graveyard and equip this card to a monster your opponent controls. Gain control of the equipped monster. During your End Phase, give control of the equipped monster to your opponent. During your Standby Phase, gain control of the equipped monster.`,
  },
  {
    id: 45452224,
    name: "Kinka-byo",
    errataId: 45452244,
    koid: 7728,
    desc: `This card cannot be Special Summoned. This card returns to its owner's hand during the End Phase of the turn it is Normal Summoned or flipped face-up. When this card is Normal Summoned or flipped face-up, you can Special Summon 1 Level 1 monster from your Graveyard. When this card is removed from the field, remove from play that monster.`,
  },
  {
    id: 45894482,
    name: "Gilasaurus",
    errataId: 45894502,
    koid: 5256,
    desc: `You can Special Summon this card from your hand. If you do, your opponent can Special Summon 1 monster from their Graveyard.`,
  },
  {
    id: 47025270,
    name: "Helping Robo for Combat",
    errataId: 47025290,
    koid: 5596,
    desc: `Each time this card destroys your opponent's monster as a result of battle, draw 1 card, then select and return 1 card from your hand to the bottom of your Deck.`,
  },
  {
    id: 47297616,
    name: "Light and Darkness Dragon",
    errataId: 47297636,
    koid: 6821,
    desc: `This card cannot be Special Summoned. While this card is face-up on the field its Attribute is also treated as DARK. When a Spell or Trap Card is activated, or the effect of an Effect Monster is activated, that activation is negated and this card loses 500 ATK and DEF. When this card is destroyed and sent to the Graveyard, select 1 monster in your Graveyard. Then destroy all cards you control, and Special Summon that monster.`,
  },
  {
    id: 47355498,
    name: "Necrovalley",
    errataId: 47355518,
    koid: 5533,
    desc: `Negate the effects of Spells, Traps, and Effect Monsters that target a card(s) in either player's Graveyard. Cards in either player's Graveyard cannot be removed from play. All "Gravekeeper's" monsters gain 500 ATK and DEF.`,
  },
  {
    id: 48092532,
    name: "D.D. Survivor",
    errataId: 48092552,
    koid: 6332,
    desc: `When this card is removed from play while face-up on your side of the field, you Special Summon it during the End Phase.`,
  },
  {
    id: 50321796,
    name: "Brionac, Dragon of the Ice Barrier",
    errataId: 50321816,
    koid: 7548,
    desc: `1 Tuner + 1 or more non-Tuner monsters
You can discard any number of cards to the Graveyard, to return the same number of cards from the field to the hand.`,
  },
  {
    id: 53183600,
    name: "Blue-Eyes Toon Dragon",
    errataId: 53183620,
    koid: 4773,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned while you control "Toon World". You can Special Summon this card from your hand (but Tributes are required if it is Level 5 or higher). This card cannot attack during the turn it is Summoned. This card cannot attack unless you pay 500 Life Points. When "Toon World" is destroyed, destroy this card. If your opponent doesn't control a Toon Monster, this card can attack your opponent directly. If your opponent controls a face-up Toon Monster, you must select it as an attack target.`,
  },
  {
    id: 55821894,
    name: "Amazoness Fighter",
    errataId: 55821914,
    koid: 5295,
    desc: `All Battle Damage to this card's controller that he/she takes from a battle involving this monster becomes 0.`,
  },
  {
    id: 56570271,
    name: "Destiny HERO - Disk Commander",
    errataId: 56570291,
    koid: 7095,
    desc: `When this card is Special Summoned from the Graveyard, draw 2 cards.`,
  },
  {
    id: 57728570,
    name: "Crush Card Virus",
    errataId: 57728590,
    koid: 4667,
    desc: `Tribute 1 DARK monster with 1000 or less ATK. Check all monsters your opponent controls, your opponent's hand, and all cards they draw (until the end of your opponent's 3rd turn after this card's activation), and destroy all monsters with 1500 or more ATK.`,
  },
  {
    id: 58996430,
    name: "Wulf, Lightsworn Beast",
    errataId: 58996450,
    koid: 7596,
    desc: `This card cannot be Normal Summoned or Set. When this card is sent from your Deck to the Graveyard, Special Summon it.`,
  },
  {
    id: 61468779,
    name: "Grandsoil the Elemental Lord",
    errataId: 61468799,
    koid: 10168,
    desc: `Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by having exactly 5 EARTH monsters in your Graveyard, and cannot be Special Summoned by other ways. When this card is Special Summoned: You can target 1 monster in either player's Graveyard; Special Summon that target to your side of the field. If this card leaves the field, skip the Battle Phase of your next turn.`,
  },
  {
    id: 61665245,
    name: "Summon Sorceress",
    errataId: 61665265,
    koid: 13554,
    desc: `2+ monsters with the same Type, except Tokens
If this card is Link Summoned: You can Special Summon 1 monster from your hand in Defense Position, to your opponent's zone this card points to. You can target 1 face-up monster this card points to; Special Summon 1 monster from your Deck in Defense Position, with the same Type as that monster, to a zone this card points to, but negate its effects. You can only use this effect of "Summon Sorceress" once per turn.`,
  },
  {
    id: 61740673,
    name: "Imperial Order",
    errataId: 61740693,
    koid: 4960,
    desc: `As long as this card remains face-up on the field, negate the effects of all Spell Cards on the field. Pay 700 Life Points during each of your Standby Phases. If you do not, this card is destroyed.`,
  },
  {
    id: 64500000,
    name: "Z-Metal Tank",
    errataId: 64500020,
    koid: 5555,
    desc: `Once per turn, during your Main Phase, you can equip this card to "X-Head Cannon" or "Y-Dragon Head" you control as an Equip Card, OR unequip it to Special Summon this card in face-up Attack Position. While equipped to a monster by this effect, that monster gains 600 ATK and DEF. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed by battle, destroy this card instead.)`,
  },
  {
    id: 64631466,
    name: "Relinquished",
    errataId: 64631486,
    koid: 4737,
    desc: `Once per turn, select 1 monster your opponent controls and equip it to this card (only 1 monster can be equipped to it at a time). This card's ATK and DEF become equal to the ATK and DEF of the monster equipped to this card. If this card is destroyed by battle, the equipped monster is destroyed instead, and any battle damage you received from the battle is also inflicted to your opponent.`,
  },
  {
    id: 65240384,
    name: "Big Shield Gardna",
    errataId: 65240404,
    koid: 4764,
    desc: `If this 1 face-down monster is targeted by a Spell Card, negate that card's activation and change this card to face-up Defense Position. If this card is attacked, change it to Attack Position at the end of the Damage Step.`,
  },
  {
    id: 65458948,
    name: "Toon Mermaid",
    errataId: 65458968,
    koid: 4734,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned while you control "Toon World". You can Special Summon this card from your hand (but Tributes are required if it is Level 5 or higher). This card cannot attack during the turn it is Summoned. This card cannot attack unless you pay 500 Life Points. When "Toon World" is destroyed, destroy this card. If your opponent doesn't control a Toon Monster, this card can attack your opponent directly. If your opponent controls a face-up Toon Monster, you must select it as an attack target.`,
  },
  {
    id: 65622692,
    name: "Y-Dragon Head",
    errataId: 65622712,
    koid: 5552,
    desc: `Once per turn, during your Main Phase, you can equip this card to "X-Head Cannon" you control as an Equip Card, OR unequip it to Special Summon this card in face-up Attack Position. While equipped to a monster by this effect, that monster gains 400 ATK and DEF. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed by battle, destroy this card instead.)`,
  },
  {
    id: 66403530,
    name: "Topologic Zeroboros",
    errataId: 66403550,
    koid: 14624,
    desc: `2+ Effect Monsters
You [b]cannot[/b] Summon/Set monsters to any Extra Monster Zone this card points to. Gains 200 ATK for each banished card. If another monster is Special Summoned to a zone a Link Monster points to, while this monster is on the field: [b]Banish[/b] all cards on the field. [b]Once[/b] [b]per turn[/b], during the [b]Standby Phase[/b] of the next turn after this card was banished by its own effect: Special Summon this banished card.`,
  },
  {
    id: 67159705,
    name: "Armored Cybern",
    errataId: 67159725,
    koid: 7412,
    desc: `Once per turn, during your Main Phase, you can equip this card to a "Cyber Dragon" you control, or to a Fusion Monster you control that lists "Cyber Dragon" as a Fusion Material Monster, OR unequip it to Special Summon this card in face-up Attack Position. Once per turn, while equipped to a monster by this effect, you can decrease the equipped monster's ATK by 1000 and destroy 1 face-up monster. (A monster can only by equipped with 1 Union Monster at a time. If the equipped monster would be destroyed, destroy this card instead.)`,
  },
  {
    id: 68005187,
    name: "Soul Exchange",
    errataId: 68005207,
    koid: 5099,
    desc: `Select 1 monster your opponent controls. This turn you can Tribute that monster as if you controlled it. You cannot conduct your Battle Phase the turn you activate this card.`,
  },
  {
    id: 68540058,
    name: "Metalmorph",
    errataId: 68540078,
    koid: 4664,
    desc: `After activation, equip this card to a monster. It gains 300 ATK and DEF. When the equipped monster attacks, it gains additional ATK equal to half the attack target's ATK, during damage calculation only.`,
  },
  {
    id: 69279219,
    name: "My Body as a Shield",
    errataId: 69279239,
    koid: 5675,
    desc: `Activate only by paying 1500 Life Points when your opponent activates a card with an effect that would destroy 1 or more monster(s) on the field. Negate the activation of that card and destroy it.`,
  },
  {
    id: 70583986,
    name: "Dewloren, Tiger King of the Ice Barrier",
    errataId: 70584006,
    koid: 7970,
    desc: `1 Tuner + 1 or more non-Tuner WATER monsters
Once per turn, you can return any number of face-up cards you control to the owner's hand. This card gains 500 ATK for each card returned to the owner's hand by this effect until the End Phase of this turn.`,
  },
  {
    id: 71645242,
    name: "Black Garden",
    errataId: 71645262,
    koid: 7904,
    desc: `When a monster is Normal or Special Summoned, except by the effect of "Black Garden", halve its ATK and Special Summon 1 "Rose Token" (Plant-Type/DARK/Level 2/ATK 800/DEF 800) to its controller's opponent's side of the field, in Attack Position. You can destroy this card and all face-up Plant-Type monsters on the field and Special Summon 1 monster with ATK equal to the total ATK of those monsters from your Graveyard.`,
  },
  {
    id: 72989439,
    name: "Black Luster Soldier - Envoy of the Beginning",
    errataId: 72989459,
    koid: 5835,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 1 LIGHT and 1 DARK monster in your Graveyard. Once during each of your turns, you can select and activate 1 of the following effects:
● Remove from play 1 monster on the field. If you activate this effect, this card cannot attack during this turn.
● If this card destroyed your opponent's monster as a result of battle, it can attack once again in a row.`,
  },
  {
    id: 75043725,
    name: "Emissary of the Afterlife",
    errataId: 75043745,
    koid: 6038,
    desc: `When this card is sent from the field to the Graveyard, each player selects 1 Level 3 or lower Normal Monster from their Deck, and adds it to their hand after showing it to the opponent. The Decks are then shuffled.`,
  },
  {
    id: 76263644,
    name: "Destiny End Dragoon",
    errataId: 76263664,
    koid: 7615,
    desc: `Destiny Hero - Plasma" + "Destiny Hero - Dogma"
A Fusion Summon of this monster can only be conducted with the above Fusion Material Monsters. Once per turn, you can destroy 1 monster your opponent controls and inflict damage to your opponent equal to its ATK. If you activate this effect, you cannot conduct your Battle Phase this turn. During your Standby Phase, if this card is in your Graveyard you can remove from play 1 "Destiny Hero" card from your Graveyard to Special Summon this card.`,
  },
  {
    id: 76862289,
    name: "Yamata Dragon",
    errataId: 76862309,
    koid: 5377,
    desc: `This card cannot be Special Summoned. This card returns to its owner's hand during the End Phase of the turn it is Normal Summoned or flipped face-up. When this card inflicts Battle Damage to your opponent, draw cards until you have 5 cards in your hand.`,
  },
  {
    id: 77084837,
    name: "Inaba White Rabbit",
    errataId: 77084857,
    koid: 5374,
    desc: `This card cannot be Special Summoned. This card returns to the owner's hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. This monster attacks your opponent's Life Points directly.`,
  },
  {
    id: 77565204,
    name: "Future Fusion",
    errataId: 77565224,
    koid: 6782,
    desc: `Send, from your Deck to the Graveyard, Fusion Material Monsters that are listed on a Fusion Monster Card, and select that 1 Fusion Monster from your Extra Deck. Special Summon a Fusion Monster from your Extra Deck with the same name as the selected Fusion Monster during your 2nd Standby Phase after this card's activation. (This Special Summon is treated as a Fusion Summon.) When this card is removed from the field, destroy the monster. When the monster is destroyed, destroy this card.`,
  },
  {
    id: 78010363,
    name: "Witch of the Black Forest",
    errataId: 78010383,
    koid: 4580,
    desc: `When this card is sent from the field to the Graveyard, select 1 monster with a DEF of 1500 or less from your Deck, show it to your opponent, and add it to your hand. Then shuffle your Deck.`,
  },
  {
    id: 78349103,
    name: "Machina Peacekeeper",
    errataId: 78349123,
    koid: 8694,
    desc: `When this card on the field is destroyed and sent to the Graveyard, you can add 1 Union Monster from your Deck to your hand. Once per turn, during your Main Phase, you can equip this card to a Machine-Type monster you control as an Equip Card, OR unequip it to Special Summon this card in face-up Attack Position. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed, destroy this card instead.)`,
  },
  {
    id: 78706415,
    name: "Fiber Jar",
    errataId: 78706435,
    koid: 5371,
    desc: `FLIP: Both players unite all their respective cards on the field, in their hands, and in their Graveyards with their respective Decks and shuffle them. Then both players draw 5 cards from their shuffled Decks.`,
  },
  {
    id: 80168720,
    name: "Darkness Approaches",
    errataId: 80168740,
    koid: 4902,
    desc: `Discard 2 cards from your hand. Select 1 face-up monster and flip it face-down, but do not change its battle position.`,
  },
  {
    id: 80604091,
    name: "Ultimate Offering",
    errataId: 80604111,
    koid: 4851,
    desc: `At the cost of 500 Life Points per monster, a player is allowed an extra Normal Summon or Set.`,
  },
  {
    id: 82301904,
    name: "Chaos Emperor Dragon - Envoy of the End",
    errataId: 82301924,
    koid: 5860,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 1 LIGHT and 1 DARK monster in your Graveyard. You can pay 1000 Life Points to send all cards in both players' hands and on the field to the Graveyard. Inflict 300 damage to your opponent for each card sent to the Graveyard by this effect.`,
  },
  {
    id: 83555666,
    name: "Ring of Destruction",
    errataId: 83555686,
    koid: 5005,
    desc: `Destroy 1 face-up monster and inflict damage to both players equal to its ATK.`,
  },
  {
    id: 87148330,
    name: "Tethys, Goddess of Light",
    errataId: 87148350,
    koid: 7560,
    desc: `When you draw a Fairy-Type monster(s), you can reveal 1 of those monsters to draw 1 more card.`,
  },
  {
    id: 87910978,
    name: "Brain Control",
    errataId: 87910998,
    koid: 4803,
    desc: `Pay 800 Life Points. Select 1 face-up monster your opponent controls. Take control of it until the End Phase.`,
  },
  {
    id: 88264978,
    name: "Red-Eyes Darkness Metal Dragon",
    errataId: 88264998,
    koid: 7557,
    desc: `You can remove from play 1 face-up Dragon-Type monster you control to Special Summon this card. Once per turn, during your Main Phase, you can Special Summon 1 Dragon-Type monster except "Red-Eyes Darkness Metal Dragon" from your hand or Graveyard.`,
  },
  {
    id: 88789641,
    name: "Hallowed Life Barrier",
    errataId: 88789661,
    koid: 6149,
    desc: `[b]Discard[/b] 1 card; you take no damage from your opponent's cards this turn, [b]also[/b] your monsters [b]cannot[/b] be destroyed by battle this turn.`,
  },
  {
    id: 89111398,
    name: "Dark Dust Spirit",
    errataId: 89111418,
    koid: 5414,
    desc: `This card cannot be Special Summoned. During the End Phase of the turn that this card is Normal Summoned or flipped face-up, return it to its owner's hand. When this card is Normal Summoned or flipped face-up, destroy all other face-up monsters.`,
  },
  {
    id: 89312388,
    name: "Elemental HERO Prisma",
    errataId: 89312408,
    koid: 7491,
    desc: `Once per turn, you can reveal 1 Fusion Monster from your Fusion Deck and send 1 of the Fusion Material Monsters listed on that card from your Deck to the Graveyard. Until the End Phase, this card's name is treated as the sent monster's name.`,
  },
  {
    id: 90502999,
    name: "Ground Collapse",
    errataId: 90503019,
    koid: 5170,
    desc: `Select 2 Monster Card Zones on the field. Neither player can use the selected zones. You cannot select a zone that is occupied by a Monster Card.`,
  },
  {
    id: 90960358,
    name: "Toon Dark Magician Girl",
    errataId: 90960378,
    koid: 5450,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned while "Toon World" is on your side of the field. You can Special Summon this monster from your hand, but Tributes are required for monsters Level 5 or more. When "Toon World" on the field is destroyed, this card is also destroyed. If your opponent doesn't control a Toon Monster, this card can attack your opponent directly. If a face-up Toon Monster is on your opponent's side of the field, you must select the Toon Monster as an attack target. This card gains 300 ATK for each "Dark Magician" or "Magician of Black Chaos" in either player's Graveyard.`,
  },
  {
    id: 91842653,
    name: "Toon Summoned Skull",
    errataId: 91842673,
    koid: 4735,
    desc: `This card cannot be Normal Summoned or Set. This card can only be Special Summoned while you control "Toon World". You can Special Summon this card from your hand (but Tributes are required if it is Level 5 or higher). This card cannot attack during the turn it is Summoned. This card cannot attack unless you pay 500 Life Points. When "Toon World" is destroyed, destroy this card. If your opponent doesn't control a Toon Monster, this card can attack your opponent directly. If your opponent controls a face-up Toon Monster, you must select it as an attack target.`,
  },
  {
    id: 94634433,
    name: "Urgent Tuning",
    errataId: 94634453,
    koid: 7920,
    desc: `Activate only during the Battle Phase. Synchro Summon 1 Synchro Monster. (Send the appropriate Synchro Material Monsters to the Graveyard.)`,
  },
  {
    id: 95503687,
    name: "Lumina, Lightsworn Summoner",
    errataId: 95503707,
    koid: 7594,
    desc: `Once per turn, you can discard 1 card to Special Summon 1 Level 4 or lower "Lightsworn" monster from your Graveyard. During each of your End Phases, send the top 3 cards of your Deck to the Graveyard.`,
  },
  {
    id: 95727991,
    name: "Catapult Turtle",
    errataId: 95728011,
    koid: 4095,
    desc: `You can Tribute 1 monster to Inflict damage to your opponent equal to half of its ATK.`,
  },
  {
    id: 96235275,
    name: "Jain, Lightsworn Paladin",
    errataId: 96235295,
    koid: 7591,
    desc: `If this card attacks an opponent's monster, it gains 300 ATK during the Damage Step only. During each of your End Phases, send the top 2 cards of your Deck to the Graveyard.`,
  },
  {
    id: 96300057,
    name: "W-Wing Catapult",
    errataId: 96300077,
    koid: 6475,
    desc: `Once per turn, you can equip this card to a "V-Tiger Jet" you control, OR unequip it to Special Summon this card in face-up Attack Position. When equipped to a monster by this card's effect, the equipped monster gains 400 ATK and DEF. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed by battle, destroy this card instead.)`,
  },
  {
    id: 96316857,
    name: "Recycle",
    errataId: 96316877,
    koid: 5845,
    desc: `During your Standby Phase: You can pay 300 LP, then target 1 non-monster in your Graveyard; return it to the bottom of your Deck.`,
  },
  {
    id: 99414168,
    name: "Elemental Mistress Doriado",
    errataId: 99414188,
    koid: 6343,
    desc: `This card can only be Ritual Summoned with the Ritual Spell Card, "Doriado's Blessing". The Attribute of this card is [b]also[/b] treated as WIND, WATER, FIRE, [b]and[/b] EARTH while it is face-up on the field.`,
  },
  {
    id: 99724761,
    name: "XZ-Tank Cannon",
    errataId: 99724781,
    koid: 5625,
    desc: `"X-Head Cannon" + "Z-Metal Tank"
This card can only be Special Summoned from your Fusion Deck by removing from play the above cards on your side of the field. (You do not use "Polymerization"). This card cannot be Special Summoned from the Graveyard. Discard 1 card from your hand to destroy 1 face-down Spell or Trap Card on your opponent's side of the field.`,
  },
];
